java_binary(
    name = "keyboardpiano",
    srcs = ["Main.java"],
    main_class = "com.augustbonds.keyboardpiano.Main",
    deps = [
        "//sdk/src/main/java/com/augustbonds/foundation",
        "//sdk/src/main/java/com/augustbonds/logging",
    ]
)

