java_binary(
    name = "keyboardpiano",
    srcs = ["Main.java"],
    main_class = "com.augustbonds.keyboardpiano.Main",
    deps = [
        "//foundation/src/main/java/com/augustbonds/foundation",
    ]
)

